### ISSUE TITLE
7.2 compatible release

### ISSUE THREAD

**Issue by dmnc** [zf1s/zend-cache#1]
Hi @unhawkable,

I can see there is a commit in master for 7.2 compatibility: https://github.com/zf1s/zend-cache/commit/3284983138a3264a0c921bacbd548668a20f0056

Is it possible you could release this as 1.12.21 please?

Dom

**Comment by falkenhawk** [comment]
I will, in the meantime use `"zf1s/zend-cache": "@dev"`

**Comment by holtkamp** [comment]
@unhawkable any other ZF1 packages you are working on / need help with? Just shout, great to see the community ensures the old ZF1 packages are still usable on new PHP versions. We are slowly deprecating them, but as always: takes longer than expected 😄

**Comment by falkenhawk** [comment]
@holtkamp me and others at my organisation can only actively maintain as many ZF1 packages as we are still using at the moment, so if you see something missing in any package please just let me know. Thank you

**Comment by unhawkable** [comment]
zend-validate/#2

**Comment by falkenhawk** [comment]
zf1s/zend-validate#2
